apiVersion: skaffold/v3
kind: Config
metadata:
  name: catalog-service
build:
  artifacts:
  - image: naveendocker007/catalog-service
    buildpacks:
      builder: gcr.io/paketo-buildpacks/builder:base
      env:
      - "BP_JVM_VERSION=17.*"
deploy:
  kubectl:
    flags:
      apply: 
      - k8s/deployment.yml
      - k8s/service.yml
